### ISSUE TITLE
How do you install this ?

### ISSUE THREAD

**Issue by praneet195** [idaholab/Topology_Generator#4]
The commands seem to do nothing

**Comment by rajpra808** [comment]
Its been long after asked this question but, I am answering this question so that it can be helpful to others
Here is how to use this tool:
1. First clone the repo
2. cd Topology_Generator
3. qmake
4. make
5. ./ns-3-generator
This will open its window
I hope this will help.

**Comment by bmeares** [comment]
[Here is a link to a solution I found for Ubuntu 20.10](https://github.com/idaholab/Topology_Generator/issues/3#issuecomment-732438190) (posted in #3).

In summary, set the `TARGET` variable, add the `focal` release of the qt4 repository, `apt update`, install `qt4-default`, `qmake`, and `make`.
